clc
clear
%% Initialize EEGLAB
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;

%% Load Dataset

%EEGlab datasets
filePath = '1_Test_In';
num_file = 1;
fileNames = ls(fullfile(filePath, "*.set"));
fileNames = string(fileNames);

%Clustering Equations
%ClusterEQs = readlines('cluster_eq.txt');

%Components to remove in ICA
%ICAComp = readlines ('cluster_eq.txt');

num_files =  size(fileNames,1);

while num_file <= num_files;

    %% 1. Load data, 
    % The data here is the preprocessed file generated by 
    % ERPProcessing_01_pretest_V2.m. This preprocessing includes filtering
    % and re-referencing
    fileName = convertStringsToChars(fileNames(num_file, 1));
    subjCode = erase(fileName,'.set')
    EEG = pop_loadset('filename',fileName,'filepath',filePath);
    EEG = eeg_checkset( EEG );
    eeglab redraw;

    %% 2. Resample Data

    new_Fs = 128;
    EEG = pop_resample(EEG, new_Fs);
    eeglab redraw;

    %% 3. Cluster data
    cluster_eq = input("Enter the cluster equation for this dataset: ")
    EEG = pop_eegchanoperator( EEG, cluster_eq, 'ErrorMsg', 'popup', 'KeepChLoc', 'on', 'Warning', 'on' ); % GUI: 13-Jul-2023 16:51:04

    %edit location of channel Cz  
    EEG=pop_chanedit(EEG, 'changefield',{10,'theta','90'},'changefield',{9,'radius','0'},'changefield',{9,'X','-1.1427e-31'},'changefield',{9,'Y','-6.2206e-16'},'changefield',{9,'Z','10.159'},'changefield',{9,'sph_theta','-90'},'changefield',{9,'sph_phi','90'},'changefield',{9,'sph_radius','10.159'},'changefield',{9,'type','EEG'},'setref',{'','LM RM'});

    %Rename and save (not sure if generating all the files in the pipeline)
    % EEG.setname='AMT018_PT_filt_REREF_cluster';
    % EEG = eeg_checkset( EEG );
    % EEG = pop_saveset( EEG, 'filename','04_AMT018_PT_filt_REREF_cluster.set','filepath','C:\\Users\\JorgeD_HirakiLab\\Documents\\UTokyo_WS2020\\Hiraki Lab\\14_Experiments\\01_Association_Memory_Task\\04_Data collection experiment\\Analysis\\EEG\\AMT018\\02_ERP\\01_Pretest');
    pop_eegplot( EEG, 1, 1, 1);
    

    %% ERPlab operations

    %% 4.Load new event list

    ElistFolder = 'EventLists';
    ElistFile = strcat (ElistFolder,'\',subjCode,'_Elist_New.txt');

    EEG= pop_overwritevent( EEG, 'code');% Script: 10-Jul-2023 14:24:10

    %load new event list
    EEG = pop_importeegeventlist( EEG, ElistFile , 'ReplaceEventList', 'on' ); % GUI: 10-Jul-2023 14:24:10

    pop_eegplot( EEG, 1, 1, 1);

    
    %% 5. Create bins
    
    %edit binlister for Test section
    EEG  = pop_binlister( EEG , 'BDF', 'Settings_TXT\binlister_3b_test.txt', 'IndexEL',  1, 'SendEL2', 'EEG&Text', 'Voutput', 'EEG' ); % GUI: 14-Jul-2023 10:04:04     
        
    %% 6. Epoch data
    EEG = pop_epochbin( EEG , [-200.0  1000.0],  'pre'); % GUI: 10-Jul-2023 16:10:43

    %Plot data to check the event markers (Optional)
    pop_eegplot( EEG, 1, 1, 1);

    eeglab redraw;

    %% 7. Eye Blink removal via ICA

    %1. Perform Independent Component Analysis for eye blink removal
    ncomp = input ("Enter number of components (nchan - 1): ");
    EEG = pop_runica(EEG, 'icatype', 'runica', 'extended',1,'interrupt','on','pca',ncomp);

    rem_comp = input("Enter the components to remove: ");

    %2. Remove selected components 
    EEG = pop_subcomp( EEG, rem_comp, 0);

    %Plot pruned dataset (Optional)
    pop_eegplot( EEG, 1, 1, 1);

    %% 8. Remove channels Fp1 (1) and Fp2 (3)

    EEG = pop_select( EEG, 'rmchannel',{'Fp1','Fp2'});
    pop_eegplot( EEG, 1, 1, 1);

    %% 9. Artifact Rejection

    %1. Perform Moving Window Artifact Rejection
    mw_thr = 100;
    EEG  = pop_artmwppth( EEG , 'Channel',  1:20, 'Flag', [ 1 2], 'LowPass',  -1, 'Threshold',  mw_thr, 'Twindow', [ -200 996], 'Windowsize',  200, 'Windowstep',  100 ); % GUI: 10-Jul-2023 17:06:39

    %3. perform Step-Like artifact rejection
    step_thr = 100;
    EEG  = pop_artstep( EEG , 'Channel',  1:20, 'Flag', [ 1 3], 'LowPass',  -1, 'Threshold',  step_thr , 'Twindow', [ -200 996], 'Windowsize',  200, 'Windowstep',  50 ); % GUI: 10-Jul-2023 17:13:29

    %Plot AR detected dataset (Optional)
    pop_eegplot( EEG, 1, 1, 1);

    %save Moving Window artifact rejection summary in textfile
    ARSumFolder = 'Output_TXT_resamp';
    ArSumFile = strcat (ARSumFolder,'\',subjCode,'_AR_Summary.txt')    
    EEG = pop_summary_AR_eeg_detection(EEG, ArSumFile); % GUI: 10-Jul-2023 17:12:10

    %Save Resulting ECG Dataset
    EEG = eeg_checkset( EEG );
    EEG_OutFolder =  '2_Test_Out_Resamp';   
    EEG_Filename = strcat(subjCode,'_proc.set');
    EEG = pop_saveset( EEG, 'filename',EEG_Filename,'filepath',EEG_OutFolder);

    %Save ERP data
    ERP_OutFolder = '3_ERP_Test_Out_Resamp';
    ERP_SetName = strcat(subjCode,'_erp');
    ERP_Filename = strcat(subjCode,'.erp');
    ERP = pop_averager( EEG , 'Criterion', 'good', 'DQ_custom_wins', 0, 'DQ_flag', 1, 'DQ_preavg_txt', 0, 'ExcludeBoundary', 'on', 'SEM', 'on' );

    ERP = pop_savemyerp(ERP, 'erpname', ERP_SetName, 'filename', ERP_Filename, 'filepath',ERP_OutFolder, 'Warning','on');

    num_file = num_file+1;

end